---
:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
staging:
  :concurrency: 10
production:
  :concurrency: 20
daemon: true

:queues:
  - default
  - mailer
  - searchkick
  - [critical, 2]